[package]
name = "qweather-sdk"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
authors = ["ZoOL <zhooul@gmail.com>"]
readme = "README.md"
description = "Client SDK to use QWeather API"
keywords = ["sdk", "qweather", "rest"]
categories = ["api-bindings"]

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "multipart"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"